TestMvc/Controllers/FourthController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ruanmou.Framework.Extension;
using Ruanmou.Framework.ImageHelper;
using TestMvc.Utility;

namespace TestMvc.Controllers
{
    public class FourthController : Controller
    {
        // GET: Fourth
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string name, string verify, string password)
        {
            LoginResult result = this.HttpContext.UserLogin(name, password, verify);
            if (result == LoginResult.Success)
            {
                if (this.HttpContext.Session["CurrentUrl"] == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    string url = this.HttpContext.Session["CurrentUrl"].ToString();
                    this.HttpContext.Session["CurrentUrl"] = null;
                    return Redirect(url);
                }
            }
            else
            {
                ModelState.AddModelError("failed", result.GetRemark());
                return View();
            }
        }

        public FileContentResult VerifyCode()
        {
            string code = "";
            var bitMap = VerifyCodeHelper.CreateVerifyCode(out code);
            HttpContext.Session["CheckCode"] = code;
            var stream=new MemoryStream();
            bitMap.Save(stream,ImageFormat.Gif);
            return File(stream.ToArray(), "image/gif");
        }

        public void Verify()
        {
            string code = "";
            var bitmap = VerifyCodeHelper.CreateVerifyCode(out code);
            HttpContext.Session["CheckCode"] = code;
            bitmap.Save(Response.OutputStream,ImageFormat.Gif);
            Response.ContentType = "image/gif";
        }


}
}

TestMvc/Views/Fourth/Login.cshtml
@using Web.Core.Extension
@model Web.Core.Models.CurrentUser

@{
    ViewBag.Title = "登录";
}

<h2>@ViewBag.Title。</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Fourth", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>使用本地帐户登录。</h4>
                <hr />
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("VerifyCode", "VerifyCode", new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBox("verify", "", new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        @*@Html.Image("/Handler/VerifyCode.ashx", "验证码图片", "点击刷新", new { onclick = "refresh(this)" }, "img")*@
                        @*@Html.Image("/self/1.verify", "验证码图片", "点击刷新", new { onclick = "refresh(this)" }, "img")*@
                        @*@Html.Image("/Fourth/VerifyCode", "验证码图片", "点击刷新", new { onclick = "refresh(this)" }, "img")*@
                        @Html.Image("/Fourth/Verify", "验证码图片", "点击刷新", new { onclick = "refresh(this)" }, "img")
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="登录" class="btn btn-default" />
                        @Html.ValidationMessage("failed")
                    </div>
                </div>
            }
        </section>
    </div>
</div>
<script>
    function refresh(obj) {
        $(obj).attr("src", "/Fourth/VerifyCode?random=" + Math.random());
    }
</script>